Repository UniversityOfHelsinkiCS/labtool, pull requests merged in 2019-12, with the labels that each got.

#1042 chore/update_dependencies
  backend/package-lock.json
  backend/package.json
  backend/server/migrations/20180504115240-commentTypeToText.js
  backend/server/migrations/20180621074213-comment-add-notified-column.js
  backend/server/migrations/20180628072216-week-add-checks.js
  backend/server/migrations/20190916101904-add-instructor-notes-to-week.js
  backend/server/migrations/20190916142838-add_dropped_field_to_studentinstance.js
  backend/server/migrations/20191011074438-add_repoToReview_field_to_code_review.js
  backend/server/migrations/20191014181554-add-maxpoints-column-to-checklist.js
  backend/server/migrations/20191106172405-add-validRegistration-column-to-studentInstance.js
  backend/server/migrations/20191108120753-add-userid-to-comment.js
  backend/server/migrations/20191111113117-add-courseinstance-to-tag.js
  labtool2.0/package-lock.json
  labtool2.0/package.json
Labels: dependencies, security issue

#1046 Move send email and CSV buttons above the students table
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: enhancement, frontend

#1045 Fix/total points above other participation
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
Labels: frontend

#1040 Final review grades; minimum requirement affecting grades
  backend/server/controllers/checklists.js
  backend/server/controllers/weeks.js
  backend/server/migrations/20191202140011-final-review-grade-minimum-requirement.js
  backend/server/models/checklistItem.js
  backend/server/models/week.js
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, full-stack, top priority

#1049 master<-trunk
  backend/package-lock.json
  backend/package.json
  backend/server/controllers/checklists.js
  backend/server/controllers/weeks.js
  backend/server/migrations/20180504115240-commentTypeToText.js
  backend/server/migrations/20180621074213-comment-add-notified-column.js
  backend/server/migrations/20180628072216-week-add-checks.js
  backend/server/migrations/20190916101904-add-instructor-notes-to-week.js
  backend/server/migrations/20190916142838-add_dropped_field_to_studentinstance.js
  backend/server/migrations/20191011074438-add_repoToReview_field_to_code_review.js
  backend/server/migrations/20191014181554-add-maxpoints-column-to-checklist.js
  backend/server/migrations/20191106172405-add-validRegistration-column-to-studentInstance.js
  backend/server/migrations/20191108120753-add-userid-to-comment.js
  backend/server/migrations/20191111113117-add-courseinstance-to-tag.js
  backend/server/migrations/20191202140011-final-review-grade-minimum-requirement.js
  backend/server/models/checklistItem.js
  backend/server/models/week.js
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: master, top priority

#1052 Show review button with pause icon if a draft exists for final review
  labtool2.0/src/components/StudentTable/StudentTableRow.js
Labels: bug

#1053 Disable tag filters that are not used by any student
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, frontend

#1054 master<-trunk
  backend/server/controllers/courseinstances.js
  backend/server/controllers/weeks.js
  backend/server/migrations/20191203172201-add_finalReviewHasPoints_column_to_course_instance.js
  backend/server/models/courseinstance.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/selectedInstanceReducer.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/tests/arrayFlatPolyfill.test.js
  labtool2.0/src/util/arrayFlatPolyfill.js
Labels: master

#1048 hex code for tag colors
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/TagLabel.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: frontend

#1055 fix/unactive email text field when filter tags
  labtool2.0/src/components/TagLabel.js
Labels: frontend

#1010 Subchecklists (check prerequisites)
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191127103039-add-prerequisite-to-checklist-item.js
  backend/server/models/checklistItem.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudent/Checklist.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/ReviewStudentCodeReview.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
Labels: EPIC, enhancement, full-stack

#1056 Confirm if the student wants to remove their registration
  labtool2.0/src/components/pages/CoursePage.js
Labels: enhancement, frontend, sprint 7 (2019)

#1057 fix/no link when copying information from another course
  backend/server/controllers/courseinstances.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
Labels: backend

#1058 When sending mass email, remove title "You've received a message from Labtool"
  backend/server/controllers/email.js
Labels: backend, enhancement, sprint 7 (2019)

#1062 Fix bugs in sprint 7
  backend/.eslintrc.js
  backend/server/controllers/checklists.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/App.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: bug, full-stack

#1059 master<-trunk
  backend/.eslintrc.js
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/migrations/20191127103039-add-prerequisite-to-checklist-item.js
  backend/server/models/checklistItem.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/App.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/TagLabel.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudent/Checklist.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/ReviewStudentCodeReview.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: master, top priority

#1069 Prerequisites only from the same category
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: enhancement, frontend

#965 The user ought to know where they are currently
  labtool2.0/src/components/LogoutButton.js
  labtool2.0/src/components/pages/Nav.css
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/tests/LogoutButton.test.js
Labels: accessibility, sprint 7 (2019), top priority, work-in-progress

#1070 Correct order for checklist items with prerequisites
  backend/server/controllers/checklists.js
  labtool2.0/src/components/pages/ReviewStudent/Checklist.js
Labels: enhancement, frontend

#1073 Random color button for tags
  labtool2.0/src/components/TagLabel.js
  labtool2.0/src/components/pages/ManageTags.js
Labels: enhancement, frontend

#1074 Invert selection for student table
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/tests/StudentTable.test.js
Labels: enhancement, frontend

#1072 Various sprint 7 bug fixes
  backend/server/controllers/checklists.js
  doc/dbdiagram-schema.txt
  doc/schema.png
  labtool2.0/src/components/TagLabel.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudent/Checklist.js
Labels: bug, sprint 7 (2019)

#1076 master<-trunk
  backend/server/controllers/checklists.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/LogoutButton.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/TagLabel.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/Nav.css
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudent/Checklist.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/LogoutButton.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: master

#1077 Remove "2.0" from Labtool in navigation menu
  labtool2.0/src/components/pages/Nav.js
Labels: frontend, sprint 7 (2019)

#1081 Hide course list (student/teacher) on My Page if no courses
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/tests/MyPage.test.js
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
Labels: enhancement, frontend

#1078 Feat/reorder checklist
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: enhancement, frontend

#1080 master<-trunk
  labtool2.0/public/index.html
  labtool2.0/src/components/pages/CreateChecklist.css
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/FakeLoginPage.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/MyPage.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
Labels: master

#1075 fix/tag_fixes
  backend/server/controllers/tags.js
  labtool2.0/src/reducers/notificationReducer.js
Labels: enhancement, full-stack

#1084 master<-trunk
  backend/server/controllers/tags.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/notificationReducer.js
Labels: master
