Repository UniversityOfHelsinkiCS/labtool, pull requests merged in 2019-09, with the labels that each got.

#575 feat/logout-button
  labtool2.0/src/components/LogoutButton.js
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/tests/LogoutButton.test.js
Labels: sprint 1

#600 Check comment permissions before posting comments
  backend/package-lock.json
  backend/package.json
  backend/server/controllers/courseinstances.js
  backend/server/helpers/course_instance_helper.js
Labels: backend, dependencies, sprint 1

#619 Make horizontal scroll bar floating; refactor CoursePage
  labtool2.0/package-lock.json
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
Labels: frontend, sprint 2

#621 Instructor review notes field, review drafts, "show all reviews" button, refactoring
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/tags.js
  backend/server/controllers/weeks.js
  backend/server/helpers/application_helper.js
  backend/server/helpers/course_instance_helper.js
  backend/server/helpers/weeks_controller_helper.js
  backend/server/migrations/20190916101904-add-instructor-notes-to-week.js
  backend/server/migrations/20190916125627-create-week-draft.js
  backend/server/models/studentinstance.js
  backend/server/models/week.js
  backend/server/models/weekdraft.js
  backend/server/routes/courseInstanceRouter.js
  backend/server/seeders/20180525094324-weeks.js
  labtool2.0/src/App.js
  labtool2.0/src/components/LogoutButton.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/services/login.js
  labtool2.0/src/services/week.js
  labtool2.0/src/store.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: sprint 2

#616 feat/json-download-upload
  labtool2.0/src/components/FileInput.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/tests/FileInput.test.js
  labtool2.0/src/tests/JsonEdit.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: frontend, sprint 2

#624 Correct project link in README
  README.md
Labels: documentation

#626 Scrollbar fixes; fix for FileInput test
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/tests/FileInput.test.js
Labels: frontend

#627 Add course import to frontend
  Kurki_simulation/responses/TKT20002.2019.K.K.1.js
  Kurki_simulation/responses/TKT20002.2019.S.K.1.js
  Kurki_simulation/responses/TKT20010.2019.K.A.1.js
  Kurki_simulation/responses/TKT20010.2019.S.K.1.js
  Kurki_simulation/responses/TKT20010.2019.S.K.2.js
  Kurki_simulation/responses/TKT20010.2019.V.K.1.js
  Kurki_simulation/responses/TKT20010.2019.V.K.2.js
  Kurki_simulation/responses/TKT20011.2019.K.A.1.js
  Kurki_simulation/responses/TKT20011.2019.S.K.1.js
  Kurki_simulation/responses/TKT20011.2019.S.K.2.js
  Kurki_simulation/responses/TKT20011.2019.V.K.1.js
  Kurki_simulation/responses/TKT20011.2019.V.K.2.js
  Kurki_simulation/responses/TKT20012.2019.K.A.1.js
  Kurki_simulation/responses/TKT20666.2019.K.A.1.js
  backend/app.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/index.js
  backend/server/helpers/course_import_helper.js
  backend/server/routes/courseImportRoutes.js
  labtool2.0/src/App.js
  labtool2.0/src/components/BackButton.js
  labtool2.0/src/components/LogoutButton.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/Notification.js
  labtool2.0/src/reducers/courseImportReducer.js
  labtool2.0/src/reducers/courseInstanceReducer.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/services/courseImport.js
  labtool2.0/src/services/login.js
  labtool2.0/src/store.js
  labtool2.0/src/tests/CourseImport.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/Courses.test.js
  labtool2.0/src/tests/FileInput.test.js
  labtool2.0/src/tests/Notification.test.js
  labtool2.0/src/tests/__snapshots__/CourseImport.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/sort.test.js
  labtool2.0/src/util/format.js
Labels: enhancement, sprint 2

#628 Teachers can see student's previous participations
  backend/server/controllers/courseinstances.js
  backend/server/helpers/application_helper.js
  backend/server/models/courseinstance.js
  backend/server/routes/courseInstanceRouter.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/reducers/studentInstanceReducer.js
  labtool2.0/src/services/studentinstances.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/format.test.js
  labtool2.0/src/util/format.js
Labels: backend, frontend, sprint 2

#629 Empty comments cannot be added
  backend/server/controllers/courseinstances.js
  labtool2.0/src/components/pages/CoursePage.js
Labels: backend, frontend, ready-in-trunk, sprint 2

#632 Better tag create/edit page
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/reducers/tagReducer.js
  labtool2.0/src/util/format.js
Labels: enhancement, frontend

#634 feat/show year and term when listing courses
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/util/format.js
Labels: frontend

#622 feat/dropped-students
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20190916142838-add_dropped_field_to_studentinstance.js
  backend/server/models/studentinstance.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: backend, enhancement, sprint 2

#642 Scroll bar fixes
  labtool2.0/src/components/HorizontalScrollable.js
Labels: frontend

#644 Use less vertical space for student table
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: frontend, sprint 2

#643 Add Save button to checklist editing
  labtool2.0/src/components/pages/CreateChecklist.js
Labels: frontend, sprint 2

#656 WIP: Added the missing star
  labtool2.0/src/components/pages/ManageTags.js
Labels: work-in-progress

#655 Added two empty spaces
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
Labels: frontend

#658 copy of checklist only goes to public review
  labtool2.0/src/components/pages/ReviewStudent.js
Labels: bug, frontend

#659 Hide dropped out students table if there are no students
  labtool2.0/src/components/pages/CoursePage.js
Labels: frontend
