Repository UniversityOfHelsinkiCS/labtool, pull requests merged in 2019-10, with the labels that each got.

#684 Modify email message; add 'Send a copy to all instructors'
  backend/server/controllers/email.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
Labels: enhancement, full-stack

#685 Try to handle shibbo 302
  backend/server/controllers/courseImport.js
  backend/server/helpers/applicationHelper.js
  labtool2.0/src/util/apiConnection.js
Labels: bug, sprint 3 (2019)

#686 Fix email send fail message
  labtool2.0/src/reducers/notificationReducer.js
Labels: bug, frontend

#682 Instructor and tag dropdown should float over scrollable area
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
Labels: frontend, sprint 3 (2019)

#697 checkboxes & bulk assign
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/MassEmailPage.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/dropdown.js
Labels: frontend, sprint 3 (2019)

#698 Width of filter by instructors in course page is fixed
  .travis.yml
  README.md
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/dropdown.js
Labels: frontend

#703 feat/The teacher can see details of a student's previous participation
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
Labels: frontend

#705 Add persisted state
  Dockerfile
  labtool2.0/package-lock.json
  labtool2.0/src/App.js
  labtool2.0/src/components/BackButton.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/hooks/legacyState.js
  labtool2.0/src/hooks/persistedState.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend

#708 Add show version stuff, adjust reload conditions
  Dockerfile.test
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/App.js
  labtool2.0/src/util/apiConnection.js
Labels: frontend

#710 Fix scroll bar when assigning instructor; fix checkboxes not unchecking
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
Labels: bug, frontend

#713 Allow courses and material URL to be set to be empty
  backend/server/controllers/courseinstances.js
Labels: backend, bug

#715 Fix typo that prevents modifying course material value
  backend/server/controllers/courseinstances.js
Labels: backend, bug

#717 [hotfix] Fix scroll bars
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: bug, frontend

#720 Fix/not show later courses
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/tests/BrowseReviews.test.js
Labels: bug, frontend

#721 Dropdown for tag filter
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, frontend, sprint 3 (2019)

#711 feat/week-review-additions
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend, sprint 3 (2019)

#714 Feat/modify codereviews enhancement
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/App.css
  labtool2.0/src/components/ConfirmationModal.js
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/Notification.css
  labtool2.0/src/components/pages/Notification.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/reducers/courseInstanceReducer.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/reducers/selectedInstanceReducer.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/Notification.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Notification.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/objectKeyFilter.js
Labels: frontend

#727 Use less horizontal space for table
  labtool2.0/src/App.css
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/Notification.css
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: frontend

#728 Add course import button to navbar
  labtool2.0/src/App.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/tests/MyPage.test.js
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
Labels: frontend

#707 Browse reviews page enhancement
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/tests/MyPage.test.js
Labels: frontend, sprint 3 (2019)

#731 Various fixes; nav; preview not scalable on review
  labtool2.0/src/App.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend

#730 Feat/arbitrary repo code reviews
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191011074438-add_repoToReview_field_to_code_review.js
  backend/server/models/codereview.js
  labtool2.0/src/components/ConfirmationModal.js
  labtool2.0/src/components/RevieweeDropdown.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/util/format.js
Labels: full-stack

#733 Allow configuring maximum points for each review
  backend/server/controllers/checklists.js
  backend/server/migrations/20191014181554-add-maxpoints-column-to-checklist.js
  backend/server/models/checklist.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: enhancement, sprint 3 (2019)

#732 Checkboxes should be larger or somehow easier to click
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend, sprint 3 (2019)

#734 Quick button to activate course
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: enhancement, frontend, sprint 3 (2019)

#736 master <- trunk
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191011074438-add_repoToReview_field_to_code_review.js
  backend/server/migrations/20191014181554-add-maxpoints-column-to-checklist.js
  backend/server/models/checklist.js
  backend/server/models/codereview.js
  backend/server/seeders/20180326073413-demo-users.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/App.css
  labtool2.0/src/App.js
  labtool2.0/src/components/ConfirmationModal.js
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/RevieweeDropdown.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/checklistReducer.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/reducers/redirectReducer.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/MassEmailPage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceStaff.test.js
  labtool2.0/src/tests/MyPage.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CourseImport.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstanceStaff.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/format.test.js
  labtool2.0/src/util/format.js
Labels: master, sprint 3 (2019)

#770 Small CSS fix
  labtool2.0/src/App.css
Labels: frontend, visual

#739 Small fixes to begin sprint 4
  backend/server/controllers/courseImport.js
  labtool2.0/src/components/BackButton.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/hooks/legacyState.js
  labtool2.0/src/hooks/persistedState.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstanceStaff.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: sprint 4 (2019)

#772 Improve tag filtering, add X button for tags
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, frontend, sprint 4 (2019)

#774 Improve dropped out students list in course page
  labtool2.0/src/App.css
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: frontend, sprint 4 (2019)

#776 Fix/remove redundant period
  Kurki_simulation/responses/2019K.js
  Kurki_simulation/responses/2019S.js
  Kurki_simulation/responses/2019V.js
  Kurki_simulation/responses/2020K.js
  Kurki_simulation/responses/2020S.js
  Kurki_simulation/responses/2020V.js
  backend/server/seeders/20180326074254-demo-courseInstance.js
  backend/server/seeders/20180326074307-demo-teacherInstances.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/format.test.js
  labtool2.0/src/util/format.js
Labels: frontend

#777 Improve other participation
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/reducers/studentInstanceReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
Labels: frontend, sprint 4 (2019)

#773 Improve bulk modify/assign UI
  labtool2.0/src/App.css
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: enhancement, frontend, sprint 4 (2019)

#782 Fix/use repo address as link
  labtool2.0/src/components/RepoLink.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/RepoLink.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/format.js
Labels: frontend, sprint 4 (2019)

#784 Show maximum points to student
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
Labels: frontend, sprint 4 (2019)

#783 Browse reviews UI improvement
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
Labels: frontend, sprint 4 (2019)

#786 fix/add comment-accordion can be opened
  labtool2.0/src/components/LabtoolAddComment.js
Labels: bug

#788 Modify tooltip if student dropped
  labtool2.0/src/components/StudentTable.js
Labels: enhancement, frontend

#792 Fix #791; modifying course doesn't break page now
  labtool2.0/src/reducers/selectedInstanceReducer.js
Labels: bug, sprint 4 (2019)

#789 master <- trunk
  Kurki_simulation/responses/2019K.js
  Kurki_simulation/responses/2019S.js
  Kurki_simulation/responses/2019V.js
  Kurki_simulation/responses/2020K.js
  Kurki_simulation/responses/2020S.js
  Kurki_simulation/responses/2020V.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/email.js
  backend/server/seeders/20180326074254-demo-courseInstance.js
  backend/server/seeders/20180326074307-demo-teacherInstances.js
  labtool2.0/src/App.css
  labtool2.0/src/components/BackButton.js
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/RepoLink.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/hooks/legacyState.js
  labtool2.0/src/hooks/persistedState.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/reducers/selectedInstanceReducer.js
  labtool2.0/src/reducers/studentInstanceReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/RepoLink.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstanceStaff.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/tests/format.test.js
  labtool2.0/src/util/format.js
Labels: master

#778 Show student stats
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: frontend, sprint 4 (2019)

#794 Remove old backend import UI
  backend/server/controllers/admin.js
  backend/server/controllers/email.js
  backend/server/controllers/logout.js
  backend/server/migrations/20190916142838-add_dropped_field_to_studentinstance.js
  backend/server/migrations/20191004093847-add_courses_page_and_course_material_field_to_courseinstanse.js
  backend/server/migrations/20191011074438-add_repoToReview_field_to_code_review.js
  backend/server/migrations/20191014181554-add-maxpoints-column-to-checklist.js
Labels: backend

#779 Button on course page for next week
  labtool2.0/src/components/pages/CoursePage.js
Labels: frontend, sprint 4 (2019)

#775 Create database table for checklist items instead of saving them as JSON
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191021103008-checklist_items_to_database_table.js
  backend/server/models/checklist.js
  backend/server/models/checklistItem.js
  backend/server/seeders/20180613100142-demo-checklists.js
Labels: backend, refactoring

#797 Improve next week button
  labtool2.0/src/components/pages/CoursePage.js
Labels: frontend, sprint 4 (2019)

#796 feat/when_registering_check_if_github_repo_exists
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/hooks/useDebounce.js
  labtool2.0/src/hooks/useGithubRepo.js
  labtool2.0/src/tests/RegisterPage.test.js
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
  labtool2.0/src/util/github.js
Labels: enhancement, frontend, sprint 4 (2019)

#795 Add "admin users"
  backend/server/controllers/tags.js
  backend/server/controllers/users.js
  backend/server/helpers/applicationHelper.js
  backend/server/helpers/courseImportHelper.js
  backend/server/helpers/courseInstanceHelper.js
  backend/server/helpers/usersControllerHelper.js
  backend/server/migrations/20191028121723-add-sysop-to-users.js
  backend/server/models/teacherinstance.js
  backend/server/models/user.js
  backend/server/routes/userRouter.js
  backend/server/seeders/20180326073413-demo-users.js
  backend/server/seeders/20180326074307-demo-teacherInstances.js
  labtool2.0/src/App.js
  labtool2.0/src/components/BackButton.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/AdminPage.js
  labtool2.0/src/components/pages/Email.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/Nav.js
  labtool2.0/src/reducers/loadingReducer.js
  labtool2.0/src/reducers/loginReducer.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/reducers/userReducer.js
  labtool2.0/src/services/login.js
  labtool2.0/src/services/user.js
  labtool2.0/src/tests/AdminPage.test.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/MassEmailPage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ModifyCourseInstanceStaff.test.js
  labtool2.0/src/tests/RegisterPage.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/SetEmail.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/selectedInstanceReducer.test.js
  labtool2.0/src/util/sort.js
Labels: enhancement, full-stack, sprint 4 (2019)

#793 feat/improve code review division
  backend/requests/bulkInsertCodeReviews.rest
  backend/requests/getStudentsForAssistant.rest
  backend/server/controllers/codeReviews.js
  labtool2.0/src/components/RevieweeDropdown.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/services/codeReview.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
Labels: full-stack

#799 Fix sorting to prevent student table from flipping every time a student is selected
  labtool2.0/src/components/pages/CoursePage.js
Labels: bug, frontend

#803 Various small fixes and code cleanup to frontend
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: bug, cleanup, frontend, sprint 4 (2019)
