Repository UniversityOfHelsinkiCS/labtool, pull requests merged in 2019-11, with the labels that each got.

#805 Fix copying checklists
  backend/server/controllers/checklists.js
  labtool2.0/src/components/JsonEdit.js
Labels: bug, sprint 4 (2019)

#806 Reload on checklist JSON edit; add button to remove IDs
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/tests/CreateChecklist.test.js
Labels: enhancement, frontend

#810 Fix reviewing when week has no maximum points defined
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ReviewStudent.js
Labels: bug, frontend, sprint 4 (2019)

#812 no link when assistant has no access to the student's other instances
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/tests/BrowseReviews.test.js
Labels: bug

#807 feat/check_if_student_has_issues_enabled
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191030103857-add-issues-enabled-field-to-studentinstance.js
  backend/server/models/studentinstance.js
  backend/server/routes/courseInstanceRouter.js
  labtool2.0/src/components/IssuesDisabledWarning.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/services/studentinstances.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
Labels: sprint 4 (2019)

#814 Round 'total max points'
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/util/format.js
Labels: bug, frontend

#813 Improve checklist editing logic
  backend/server/controllers/checklists.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/pages/CreateChecklist.js
Labels: enhancement, sprint 4 (2019)

#815 Fix/changing names breaks already used checklist
  backend/server/controllers/weeks.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/reducers/weekReviewReducer.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend

#818 Various sprint 4 fixes
  labtool2.0/src/components/FileInput.js
  labtool2.0/src/components/JsonEdit.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/services/studentinstances.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: frontend, sprint 4 (2019)

#821 [hotfix] db schema
  backend/server/migrations/20191021103008-checklist_items_to_database_table.js
  backend/server/models/checklistItem.js
Labels: master

#823 Prevent student selection leak
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
Labels: bug, frontend

#801 Major refactoring to most components
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/users.js
  backend/server/migrations/20191021103008-checklist_items_to_database_table.js
  backend/server/models/checklist.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewCodeReview.js
  labtool2.0/src/components/WeekReview/WeekReviewComment.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/AdminPage.js
  labtool2.0/src/components/pages/AdminPage/AdminCourseList.js
  labtool2.0/src/components/pages/AdminPage/AdminUserList.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/Header.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/StudentRegister.js
  labtool2.0/src/components/pages/CoursePage/StudentWeeks.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/components/pages/RegisterPage/GitHubRepoWarning.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudent/PreviousWeekDetails.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/RegisterPage.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/WeekReviews.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/tests/__snapshots__/WeekReviews.test.js.snap
  labtool2.0/src/util/format.js
Labels: cleanup, full-stack, refactoring

#846 Upgrade to sequelize v5
  backend/package-lock.json
  backend/server/controllers/assistants.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/users.js
  backend/server/controllers/weeks.js
  backend/server/helpers/courseInstanceHelper.js
Labels: backend, bug

#848 Fix further errors caused by upgrade
  backend/server/controllers/courseImport.js
  backend/server/controllers/courseinstances.js
  backend/server/helpers/courseInstanceHelper.js
  backend/server/models/courseinstance.js
Labels: backend, bug

#849 Fix repo issue checking
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
Labels: bug, frontend

#847 Export students as CSV
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: enhancement, frontend

#866 Improve horizontal scrolling
  labtool2.0/src/components/HorizontalScrollable.js
Labels: enhancement, frontend, sprint 5 (2019)

#867 Modify teacher/tag assignment; hide instructor if empty
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, frontend, sprint 5 (2019)

#865 Security stuff, add userId to Comment
  backend/server/controllers/admin.js
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/login.js
  backend/server/controllers/logout.js
  backend/server/controllers/tags.js
  backend/server/controllers/users.js
  backend/server/controllers/weeks.js
  backend/server/helpers/checklistHelper.js
  backend/server/helpers/codeReviewHelper.js
  backend/server/helpers/courseInstanceHelper.js
  backend/server/migrations/20191108120753-add-userid-to-comment.js
  backend/server/models/comment.js
  backend/server/routes/courseInstanceRouter.js
Labels: backend, bug

#870 Code review page improvements
  backend/server/controllers/codeReviews.js
  labtool2.0/src/components/RevieweeDropdown.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.css
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/reducers/codeReviewReducer.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
Labels: enhancement, frontend, sprint 5 (2019)

#868 Feat/notification if new comment
  backend/requests/updateComments.rest
  backend/server/controllers/courseinstances.js
  backend/server/helpers/courseInstanceHelper.js
  backend/server/migrations/20191107191810-add_isRead_field_to_comment.js
  backend/server/models/comment.js
  backend/server/routes/courseInstanceRouter.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/reducers/coursePageReducer.js
  labtool2.0/src/services/comment.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: full-stack

#873 Points should be a required field on week review
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: bug, frontend, good first issue, sprint 5 (2019)

#872 Various bug fixes for sprint 5 master
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseinstances.js
  backend/server/seeders/20180525111653-demo-comments.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/Notification.css
  labtool2.0/src/tests/BrowseReviews.test.js
Labels: bug, sprint 5 (2019)

#876 Better error message for issue checking
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
Labels: enhancement, frontend

#878 Display warning to teacher and student if repo does not exist
  backend/server/controllers/courseinstances.js
  backend/server/migrations/20191111103110-add-repo-exists-to-studentInstance.js
  backend/server/models/studentinstance.js
  labtool2.0/src/components/RepoAccessWarning.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, full-stack

#861 Fix register page bug
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/hooks/useGithubRepo.js
  labtool2.0/src/tests/RegisterPage.test.js
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
Labels: bug, frontend

#882 fix/move buttons
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
Labels: frontend

#884 repoExists checks for code review page
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
Labels: enhancement, frontend, sprint 5 (2019)

#842 Fix all the spelling errors on error messages
  backend/server/controllers/admin.js
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/login.js
  backend/server/controllers/logout.js
  backend/server/controllers/tags.js
  backend/server/controllers/users.js
  backend/server/controllers/weeks.js
Labels: full-stack, sprint 5 (2019), visual

#889 Do not enter refresh loop if cannot connect to backend
  labtool2.0/src/util/apiConnection.js
Labels: enhancement, frontend

#883 master <- trunk
  backend/package.json
  backend/server/controllers/admin.js
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseImport.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/login.js
  backend/server/controllers/logout.js
  backend/server/controllers/tags.js
  backend/server/controllers/users.js
  backend/server/controllers/weeks.js
  backend/server/migrations/20191111103110-add-repo-exists-to-studentInstance.js
  backend/server/models/studentinstance.js
  labtool2.0/src/components/RepoAccessWarning.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/hooks/useGithubRepo.js
  labtool2.0/src/tests/RegisterPage.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/apiConnection.js
Labels: master, sprint 5 (2019)

#862 refactor/db_table_for_week_checks
  backend/server/controllers/courseinstances.js
  backend/server/controllers/weeks.js
  backend/server/migrations/20191105161629-reviewcheck_table.js
  backend/server/models/reviewcheck.js
  backend/server/models/week.js
Labels: full-stack, refactoring

#921 Do not select first option on blur
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/dropdown.js
Labels: bug, frontend, sprint 5 (2019)

#919 Add back button when giving week review
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: enhancement, frontend

#918 Checklist items and categories are ordered
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/weeks.js
  backend/server/helpers/courseInstanceHelper.js
  backend/server/migrations/20191105161629-reviewcheck_table.js
  backend/server/migrations/20191113105926-add-order-to-checklist-item.js
  backend/server/models/checklistItem.js
  backend/server/routes/courseInstanceRouter.js
  backend/server/seeders/20180613100142-demo-checklists.js
Labels: backend, enhancement

#922 Mass email fixes
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/sort.js
Labels: enhancement, frontend

#926 Clearer symbols for issue checking
  labtool2.0/src/components/IssuesDisabledWarning.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
Labels: enhancement, frontend, sprint 5 (2019)

#869 Show less stats when they are not needed
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
Labels: frontend, sprint 5 (2019), visual

#843 Advance-button should have text & no confirmation
  backend/server/controllers/weeks.js
  backend/server/migrations/20191114101837-week-string-to-text.js
  backend/server/migrations/20191114102347-comment-string-length.js
  backend/server/models/week.js
  backend/server/utils/logger.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/Header.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: frontend, sprint 5 (2019)

#928 [HOTFIX] Fixes to review and comment
  backend/server/controllers/weeks.js
  backend/server/migrations/20191114101837-week-string-to-text.js
  backend/server/migrations/20191114102347-comment-string-length.js
  backend/server/models/week.js
  backend/server/utils/logger.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/pages/CoursePage/Header.js
  labtool2.0/src/components/pages/ReviewStudent.js
Labels: bug, full-stack, master

#930 [Urgent] Edit final review
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
Labels: enhancement, frontend, master

#881 Tags can be associated with a course
  backend/server/controllers/tags.js
  backend/server/migrations/20191111113117-add-courseinstance-to-tag.js
  backend/server/models/tag.js
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/reducers/tagReducer.js
  labtool2.0/src/tests/BrowseReviews.test.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/ModifyCourseInstanceCodeReviews.test.js
  labtool2.0/src/tests/ReviewStudent.test.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/util/sort.js
Labels: enhancement, full-stack

#841 Course import changes
  backend/server/helpers/applicationHelper.js
  backend/server/helpers/courseImportHelper.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CourseImport.js
Labels: backend, enhancement, full-stack, sprint 5 (2019)

#844 Change "Current week" to a dropdown
  backend/server/controllers/courseinstances.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: frontend, sprint 5 (2019)

#936 feat/code_review_symbols
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/tests/StudentTable.test.js
Labels: enhancement, frontend

#935 Bug fixes for sprint 5 master<-trunk
  backend/server/controllers/courseinstances.js
  backend/server/models/studentinstance.js
  labtool2.0/src/components/MarkdownTextArea.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewCodeReview.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/reducers/coursePageLogicReducer.js
Labels: bug

#938 Remove comment length restriction
  backend/server/migrations/20191114102347-comment-string-to-text.js
  backend/server/models/comment.js
  labtool2.0/src/components/LabtoolAddComment.js
Labels: enhancement, full-stack

#939 Fix email newlines; fix dropdown cutoff
  backend/server/controllers/email.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: bug, full-stack

#943 master <- trunk for bug fixes
  backend/server/controllers/email.js
  backend/server/models/comment.js
  labtool2.0/src/components/LabtoolAddComment.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: master

#934 Horizontally scrollable fixes
  labtool2.0/src/components/HorizontalScrollable.js
Labels: enhancement, frontend, sprint 5 (2019)

#968 Course title should be a link on the review page
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
Labels: frontend, sprint 6 (2019)

#972 Fix/more intuitive to set max points for a week in checklist
  backend/server/controllers/checklists.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: frontend

#975 only show email button for latest comment
  labtool2.0/src/components/LabtoolComment.js
  labtool2.0/src/components/WeekReview/WeekReviewComment.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
Labels: frontend, visual

#978 fix/show the points if a code review has no link but was graded
  labtool2.0/src/components/StudentTable/StudentTableRow.js
Labels: frontend

#969 Update CSV, separate first and last names, add instructor
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: sprint 6 (2019), top priority

#985 Point rounding with Points
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/Points.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/WeekReview/WeekReviewCodeReview.js
  labtool2.0/src/components/WeekReview/WeekReviewComment.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
  labtool2.0/src/tests/__snapshots__/WeekReviews.test.js.snap
  labtool2.0/src/util/format.js
Labels: enhancement, frontend, visual

#986 Fix/intuitive max points in checklist
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/tests/CreateChecklist.test.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: frontend

#987 Change 'invalid registration' to 'mistaken registration'
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/tests/__snapshots__/StudentTable.test.js.snap
Labels: enhancement, frontend

#973 Only one checklist for code reviews
  backend/server/controllers/checklists.js
  backend/server/migrations/20191113104046-codereview_checklists.js
  backend/server/migrations/20191120100131-checklist-codereview-boolean.js
  backend/server/models/checklist.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/WeekReview/WeekReviewCodeReview.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/ReviewStudentCodeReview.test.js
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
Labels: enhancement, frontend, sprint 6 (2019)

#989 Fix tag selection bug on ModifyTags
  labtool2.0/src/components/pages/ManageTags.js
Labels: bug, frontend

#974 Scrolling fixes on Chrome
  labtool2.0/src/App.css
  labtool2.0/src/components/HorizontalScrollable.js
Labels: bug, frontend, visual

#964 feat/checklist minimum requirement
  backend/server/controllers/checklists.js
  backend/server/migrations/20191118163146-add_minimum_requirement_column_to_checklist_item.js
  backend/server/models/checklistItem.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: enhancement

#942 feat/add_document_title
  labtool2.0/package-lock.json
  labtool2.0/package.json
  labtool2.0/src/components/DocumentTitle.js
  labtool2.0/src/components/HorizontalScrollable.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/pages/AdminPage.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/Email.js
  labtool2.0/src/components/pages/LoginPage.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CourseImport.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/LoginPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstanceStaff.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
  labtool2.0/src/tests/__snapshots__/SetEmail.test.js.snap
Labels: accessibility, frontend

#993 Only check GitHub repositories
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
Labels: sprint 6 (2019), top priority

#988 Only show course tags if duplicate names with global tag
  labtool2.0/src/components/StudentTable.js
  labtool2.0/src/tests/StudentTable.test.js
Labels: enhancement, frontend

#994 Fix/issue checking bugs
  backend/server/controllers/courseinstances.js
  backend/server/helpers/courseInstanceHelper.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/RegisterPage.js
Labels: bug, full-stack, top priority

#992 changes to activate banner in course page
  doc/dbdiagram-schema.txt
  doc/schema.png
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: enhancement, frontend

#995 Sort importable courses by start date and name
  labtool2.0/src/components/pages/CourseImport.js
Labels: enhancement, frontend

#999 master<-trunk
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherHeader.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: master

#977 Use fi_FI locale sorting
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/util/sort.js
Labels: enhancement, frontend

#1004 Update backend permissions
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/tags.js
Labels: backend, bug

#1005 master<-trunk
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/tags.js
  labtool2.0/src/components/StudentTable/StudentTableRow.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/tests/StudentTable.test.js
  labtool2.0/src/util/sort.js
Labels: master, sprint 6 (2019)

#1000 Feat/remove mistaken registration
  backend/server/controllers/users.js
  backend/server/migrations/20191125133715-add_CASCADE_to_toReview_in_CodeReviews.js
  backend/server/models/codereview.js
  backend/server/routes/userRouter.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/services/studentinstances.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
Labels: full-stack

#997 Copy everything from another course instance
  backend/server/controllers/courseinstances.js
  backend/server/models/checklist.js
  backend/server/routes/courseInstanceRouter.js
  backend/server/seeders/20180613100142-demo-checklists.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/reducers/notificationReducer.js
  labtool2.0/src/services/courseInstance.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
Labels: enhancement, full-stack, sprint 6 (2019)

#1009 Error message on failed code review link submit
  backend/server/controllers/codeReviews.js
  labtool2.0/src/reducers/notificationReducer.js
Labels: bug, frontend

#1001 fix/error handling
  backend/server/controllers/assistants.js
  backend/server/controllers/checklists.js
  backend/server/controllers/codeReviews.js
  backend/server/controllers/courseinstances.js
  backend/server/controllers/email.js
  backend/server/controllers/tags.js
  backend/server/controllers/users.js
  labtool2.0/src/components/Error.js
  labtool2.0/src/components/pages/AdminPage.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/Email.js
  labtool2.0/src/components/pages/LoginPage.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/reducers/loadingReducer.js
Labels: enhancement, full-stack

#967 Trim URL so that whitespace at beginning or end won't reject it
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: accessibility, bug, sprint 6 (2019)

#1003 Week amount validation
  backend/server/controllers/courseinstances.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: backend, bug, work-in-progress

#1011 Feat/cache for importable courses
  backend/package-lock.json
  backend/package.json
  backend/server/helpers/applicationHelper.js
Labels: backend

#1014 Different looking buttons for add new topic and checkbox in checklist creation/editing
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
Labels: enhancement, frontend

#1017 Use checkbox to set code reviews as visible/unvisible
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage/CodeReviewCheckbox.js
  labtool2.0/src/reducers/selectedInstanceReducer.js
  labtool2.0/src/tests/ModifyCourseInstancePage.test.js
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
Labels: frontend

#1018 mark comments as read on reply
  labtool2.0/src/components/WeekReview/WeekReviewCodeReview.js
  labtool2.0/src/components/WeekReview/WeekReviewWeek.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/reducers/coursePageReducer.js
Labels: enhancement, frontend

#970 Move the point total closer to the user's name
  labtool2.0/src/components/TotalPoints.js
  labtool2.0/src/components/WeekReviews.js
  labtool2.0/src/components/pages/BrowseReviews/StudentCard.js
  labtool2.0/src/components/pages/CoursePage/StudentInfo.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/__snapshots__/WeekReviews.test.js.snap
Labels: accessibility, sprint 6 (2019)

#1020 Close panel on course open; proptype fixes
  labtool2.0/src/components/DocumentTitle.js
  labtool2.0/src/components/Error.js
  labtool2.0/src/components/MissingMinimumRequirements.js
  labtool2.0/src/components/pages/AdminPage.js
  labtool2.0/src/components/pages/BrowseReviews.js
  labtool2.0/src/components/pages/CourseImport.js
  labtool2.0/src/components/pages/CoursePage.js
  labtool2.0/src/components/pages/CoursePage/TeacherBulkForm.js
  labtool2.0/src/components/pages/CoursePage/TeacherMain.js
  labtool2.0/src/components/pages/Courses.js
  labtool2.0/src/components/pages/CreateChecklist.js
  labtool2.0/src/components/pages/LoginPage.js
  labtool2.0/src/components/pages/ManageTags.js
  labtool2.0/src/components/pages/MassEmailPage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceCodeReviews.js
  labtool2.0/src/components/pages/ModifyCourseInstancePage.js
  labtool2.0/src/components/pages/ModifyCourseInstanceStaff.js
  labtool2.0/src/components/pages/MyPage.js
  labtool2.0/src/components/pages/RegisterPage.js
  labtool2.0/src/components/pages/ReviewStudent.js
  labtool2.0/src/components/pages/ReviewStudentCodeReview.js
  labtool2.0/src/tests/CoursePage.test.js
  labtool2.0/src/tests/__snapshots__/BrowseReviews.test.js.snap
  labtool2.0/src/tests/__snapshots__/CourseImport.test.js.snap
  labtool2.0/src/tests/__snapshots__/CoursePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/Courses.test.js.snap
  labtool2.0/src/tests/__snapshots__/CreateChecklist.test.js.snap
  labtool2.0/src/tests/__snapshots__/LoginPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/MassEmailPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstancePage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ModifyCourseInstanceStaff.test.js.snap
  labtool2.0/src/tests/__snapshots__/MyPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/RegisterPage.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudent.test.js.snap
  labtool2.0/src/tests/__snapshots__/ReviewStudentCodeReview.test.js.snap
  labtool2.0/src/tests/__snapshots__/SetEmail.test.js.snap
Labels: bug, frontend, refactoring

#966 Double the size of the margins
  labtool2.0/src/App.css
Labels: accessibility, sprint 6 (2019), visual

#1023 back button should navigate to editing page after json modification
  labtool2.0/src/components/pages/CreateChecklist.js
Labels: frontend

#1024 master<-trunk
  labtool2.0/src/App.css
  labtool2.0/src/components/pages/CreateChecklist.js
Labels: master
